### ISSUE TITLE
Conditions not showing

### ISSUE THREAD

**Issue by dmdude165** [kandashi/condition-automation#12]
Hi, your conditions are not showing in my game, I have updated all modules and the game system.
Conditions that are supposed to be shown: https://s7.gifyu.com/images/Speed-Tests.gif
What I see: https://prnt.sc/ukkldy

Any advice to help me figure this issue out?

Cheers

**Comment by kandashi** [comment]
You must have Combat Utility Belt installed with enchanced conditions enabled
