### ISSUE TITLE
Cannot use non- .svg images for conditions

### ISSUE THREAD

**Issue by dstein766** [kandashi/condition-automation#15]
This is an undocumented constraint of Condition Automation (and, I would argue, a serious design problem).

I have replaced all *.svg condition artwork with my own combo of .png and .webp artwork using CUB Condition Lab.  This breaks Condition Automation as it assumes all artwork is named <condition>.svg.  Can support be added to EITHER:
1) Ignore the name of the artwork entirely and use the condition name defined in CUB's Condition Lab, or
2) Ignore the filename extension of the artwork when resolving the condition name.

From a design standpoint, I personally think deriving the condition name from the artwork filename is not a good choice.  The true condition name is whatever the user defined in Condition Lab.  There's zero requirement (in Condition Lab) that the filename have any relationship to the condition name.  I can (and should be able to) define a condition called MyCondition and associate that with artwork with a random name like blue-bolt.png.  If I use Condition Automation I'm forced to rename my artwork mycondition.svg or it won't work.   Further, it "breaks" Condition Lab because it puts undocumented restraints on Condition Lab.  I can't go back later and decide to associate yellow-square.webp to MyCondition [as Condition Lab both allows and expects me to do]...I'm again forced to rename yellow-square.webp -> mycondition.svg.

**Comment by dstein766** [comment]
BTW:  replacing your current regex with:
  const effectRegExp = new RegExp("([a-z-_]+)([0-9]+)?\.(svg|png|webp|jpg)", 'i');
would be a brute-force approach to option #2 above.  It isn't great because it still makes assumptions about allowed extensions, but should work in most cases.

**Comment by kandashi** [comment]
I have tried to implement option 2 before, however it has not worked so-far. Option 1 is a good idea if I can locate a way to filter by effect name rather than icon name I will do that. 
Thanks for the ideas :)

**Comment by kandashi** [comment]
Pushed an update to resolve with option 2, I cannot find a way to link back to CUB Condition Lab easily to determine the name of the condition applied rather than the name of the icon.
