### ISSUE TITLE
Speed Modifications Not Working

### ISSUE THREAD

**Issue by JLtheking2** [kandashi/condition-automation#17]
This part of the mod does not seem to be working with the latest stable version of Foundry 0.7.5, and the latest version of CUB.

Flying works though!

**Comment by kandashi** [comment]
There's a reason it isn't flagged as compatible with 0.7 5 🙃

This part of the system is going to be removed as soon as the way to store speed changes in the 5e system. Then it will be possible with just CUB

**Comment by kandashi** [comment]
Should be fixed in newest release
