### ISSUE TITLE
Conflict with JitsiWebRTC Module

### ISSUE THREAD

**Issue by bekriebel** [kandashi/condition-automation#18]
With the JitsiWebRTC module, we need to read a config from the Jitsi server being connected to. Unfortunately, this config sets their values using the `config` object that this module is using. This causes the Jitsi module to fail if this module is active.

If you don't mind, I'm going to submit a Pull Request to rename the object in this module since we can't change it on the Jitsi Server side.

**Comment by kandashi** [comment]
Im doing a rework of this now, but will try to include this change :)
