### ISSUE TITLE
attributes.speed deprecated in favor of attributes.movement object

### ISSUE THREAD

**Issue by rsimoes** [kandashi/condition-automation#21]
https://gitlab.com/foundrynet/dnd5e/-/commit/fb386e73dcb8b059737cbb8793f798bef0b0527a

Newly-created actors already lack a value for it.

**Comment by kandashi** [comment]
Looks like you are on an old version, the V2 version dosnt effect movement at all

**Comment by rsimoes** [comment]
Sure enough. Sorry about that!
