### ISSUE TITLE
Please add PF2E Support?

### ISSUE THREAD

**Issue by JamzTheMan** [kandashi/condition-automation#23]
Love the "flying" effect and works great with PF2E and was excited to try the Blinded effect with Perfect Vision but it doesn't seem to work with the PF2E system :(

I added some logs to `Hooks.on("preCreateActiveEffect", async (actor, effects, options, someID)` and it never fires, most likely because I don't think PF2E uses Active Effects perhaps?

**Comment by kandashi** [comment]
Im not sure about the pf2e system, but I can take a look at some point

**Comment by JamzTheMan** [comment]
quick work, awesome! Thanks for the support! :D
