### ISSUE TITLE
Settings for: Bulge, Shadow

### ISSUE THREAD

**Issue by HaydenReeve** [kandashi/condition-automation#38]
Hi there,

I really like the mod, although I was hoping you might consider a few changes to settings. There are a few reasons for this.

In our campaign, our tokens look a little like this:
![image](https://user-images.githubusercontent.com/39004735/108592982-ea27a280-73ab-11eb-9185-58b401064e97.png)

And, to be honest, it's a really cool flying effect. Down to 50ft here:
![image](https://user-images.githubusercontent.com/39004735/108592995-104d4280-73ac-11eb-94b1-2194278e8b63.png)

The problem starts to occur:
![image](https://user-images.githubusercontent.com/39004735/108593004-20652200-73ac-11eb-8187-f51d2d249e39.png)

As you get lower to the ground:
![image](https://user-images.githubusercontent.com/39004735/108593016-2a872080-73ac-11eb-94e4-bf10c3591791.png)

And generally looks pretty funky:
![image](https://user-images.githubusercontent.com/39004735/108593031-34a91f00-73ac-11eb-92a9-bc88bfeb5a5d.png)

I was hoping if maybe you would consider:
- Adding an option to disable the Bulge Effect entirely?
- More drastically changing the shadow distance? So it's very close to the token at 5ft, but far away (like it currently is) at 100ft?

Thank you for any consideration!

**Comment by kandashi** [comment]
I'll look into it

**Comment by HaydenReeve** [comment]
Hey! Thanks for the fix.

I was having a look at potential alternatives in animations, and there's a few here that look pretty good on lower values. I believe you're using the TokenMagic portfolio right?

https://giant.gfycat.com/WeeklyPowerlessAmericancrocodile.webm

Playing with Evade Stance on lower numbers seems to look really good.

Anyway, I thought I'd throw that out there.

Thanks again.
