### ISSUE TITLE
Suggestion: Compability with PF1 system

### ISSUE THREAD

**Issue by ArdonDaros** [kandashi/condition-automation#39]
Would it be possible to make this module's automated Blind-setting compatible with PF1 system? Thank you.

**Comment by kandashi** [comment]
A few questions:

- does the `blinded` box in the buffs tab have any mechanical ef

**Comment by ArdonDaros** [comment]
I don’t think so, no.


Lähettäjä: kandashi<mailto:notifications@github.com>
Lähetetty: keskiviikko 24. helmikuuta 2021 15.37
Vastaanottaja: kandashi/condition-automation<mailto:condition-automation@noreply.github.com>
Kopio: ArdonDaros<mailto:voutilainenantti@hotmail.com>; Author<mailto:author@noreply.github.com>
Aihe: Re: [kandashi/condition-automation] Suggestion: Compability with PF1 system (#39)


A few questions:

  *   does the blinded box in the buffs tab have any mechanical ef
