### ISSUE TITLE
Configuration for other languages

### ISSUE THREAD

**Issue by mech-tools** [kandashi/condition-automation#5]
Hello,

Thx for that module!
Do you think it's possible to create some configuration to map English conditions to translated conditions?

**Comment by kandashi** [comment]
That is a good point. I'm not sure about translations at the moment, if you could ping me on discord and send me some screenshots I might be able to do something :)

**Comment by mech-tools** [comment]
Hello,

The names of the conditions are hardcoded in your code. E.g: ['blind', 'blinded']
I would suggest some kind of custom settings where the user can map a specific condition to a custom string.

I think a simple table in the gm settings with as much text fields as you have conditions hardcoded in the code.

blinded -> text field for translation
grappled -> test field for translation
...

**Comment by kandashi** [comment]
This is possibly being integrated into CUB, so that would come with that change

**Comment by kandashi** [comment]
This function is merged into CUB now, closing
