### ISSUE TITLE
Condition Automation BUG in 0.8.7

### ISSUE THREAD

**Issue by szefo09** [kandashi/condition-automation#52]
Using Foundry 0.8.7, D&D5e 1.3.5,
Enabling Blind condition on and off twice or more causes this error to pop up.

https://user-images.githubusercontent.com/37833135/122653578-c69c1b00-d145-11eb-899d-8ac10a85e82b.mp4

**Comment by Ssezra** [comment]
Can confirm that this error/issue still exists in 0.8.8 and can only be resolved temporarily by a screen refresh.

**Comment by kandashi** [comment]
This is somewhat of a core bug unfortunatly
